#!/bin/bash

# cleans unused vim undofile 
# This script assumes that you store undofile in a seperated directory

UNDO_PATH="$HOME/.cache/undodir"
THRESHOLD="30" # in day, if the last modified time is beyond this value, the undofile will be deleted
REMOVE_LOG="/tmp/undoclean-log"

E_WRONGARGS=65
printhelp() {
    echo "Usage: $(basename "$0") [THRESHOLD] [PATH]"
    exit $E_WRONGARGS
}

case "$1" in
    "" ) ;;
    *[!0-9]* ) printhelp ;; 
    * ) THRESHOLD=$1 ;;
esac

if [ -n "$2" ]
then
    if [ -d "$2" ]
    then
        UNDO_PATH=$2
    else
        echo "$2 is not a directory!"
    fi
fi

echo "This script will deleted all the vim undo file in $UNDO_PATH that has not been modified for at least $THRESHOLD days"

find "$UNDO_PATH" -mtime "+$THRESHOLD" -print -delete | tee "$REMOVE_LOG"

echo "done, a log has been created at $REMOVE_LOG"
